update to devs in pom.xml + directory exclusion in gitignore
web-servers/noe-core pull request #151
Opened 2023-01-26 12:03 UTC by PaulLodge

2023-01-26 13:19 UTC, AdamKrajcik approved these changes
LGTM.

2023-01-26 13:20 UTC, AdamKrajcik requested changes

2023-01-26 13:20 UTC, AdamKrajcik commented on pom.xml
> +          <name>Sanitago Gala</name>
Typo.

2023-01-26 14:27 UTC, PaulLodge commented on pom.xml
> +          <name>Sanitago Gala</name>
oops yep 🤪

2023-01-26 14:30 UTC, AdamKrajcik approved these changes
LGTM.

2023-01-30 10:58 UTC, sgala approved these changes
Everything looks right to me

2023-01-30 11:22 UTC, merged